# This is the script used to create the embeddings for the descriptions of the nodes retrieved from neo4j. 
# As it is for testing and optimisation purposes, the script has to be general enough to be used for different embedding models.

#The models that will be tested are:
# Baseline (lexical matching)
#  - BM 25

# Semantic matching 
#  - OpenAI embedding model (text-embedding-3-small) - Small and large to be tested to see the difference in performance and computational cost.
#  - OpenAI embedding model (text-embedding-3-large)
#  - Qwen3-embedding-8B
#  - BAAI BGE-M3
#  - nvidia-llama-embed-nemotron-8b
#  - Jina Embeddings v3
#  - ManuBERT
#  - SciDeBERTa
#  - ColBERT v2
#  - E5-LARGE
#  - llama-3-8b
#  - Gemma-2B
#  - KaLM 12b - to be tested if it can be used for embedding generation and if it is computationally feasible to use it for this purpose.
#  - Voyage AI for proprietary - not goign to use proprietary models for the embedding generation, but it will be used for the retrieval process to see how it performs when using the embeddings generated by the other models. Serves as a benchamrk to test against.


#Complete list so far:
#  - ManuBERT (Domain speicifc model for manufacturing)
#  - BAAI BGE-M3
#  - ColBERT v2 (Late interaction model)
#  - E5-LARGE
#  - nvidia-llama-embed-nemotron-8b (top 3 on MTEB)
#  - OpenAI embedding model (text-embedding-3-large)
#  - OpenAI embedding model (text-embedding-3-small)
#  - Qwen3-embedding-8B (top 3 on MTEB)
#  - Qwen3-Embedding-0.6B (Smaller version of Qwen3-embedding-8B, to be tested if it can be used for embedding generation and if it is computationally feasible to use it for this purpose.)
#  - Qodo-Embed-1-7B ( high on ranking tasks)
#  - Qodo-Embed-1-1.5B ( high on ranking tasks, but smaller)
#  - lightonai/LateOn-Code ( high on ranking tasks)
#  - Voyage-4 - The models by voyage specialise in retrieval
#  - Voyage-code-3
#  - voyageai/voyage-4-nano - test the open version from hugging face. 









# code structure:
# 1. Load the data from neo4j - Retrieve all the app IDs and their metadescriptions and store them in a dataframe.
# 2. Run the model and create the embeddings for the descriptions of the nodes retrieved from neo4j. 
# 3. Store the embeddings back on the node with the id - the naming convention should be "embedding_model_name_embedding" (e.g. "text-embedding-3-small_embedding") to avoid confusion and to be able to easily retrieve the embeddings later on for the retrieval process.

"""
Embedding Generator Script (EGS)yes

Goal:
1) Load node descriptions from Neo4j.
2) Embed them using a selected model.
3) Store embeddings back on the nodes using a consistent property name.

Notes:
- API keys must be kept outside of code. Use a .env file (ignored by git).
- This script is intentionally model-agnostic: you choose the provider and model at runtime.
"""

from __future__ import annotations

import argparse
import os
import re
import time
from dataclasses import dataclass
from typing import Iterable, List, Optional

from neo4j import GraphDatabase
from dotenv import load_dotenv

try:
	from openai import OpenAI
except Exception:  # pragma: no cover - optional dependency
	OpenAI = None  # type: ignore[assignment]

try:
	import voyageai
except Exception:  # pragma: no cover - optional dependency
	voyageai = None  # type: ignore[assignment]

try:
	from sentence_transformers import SentenceTransformer
except Exception:  # pragma: no cover - optional dependency
	SentenceTransformer = None  # type: ignore[assignment]

try:
	from transformers import AutoTokenizer, AutoModel
	import torch
	import torch.nn.functional as torch_f
except Exception:  # pragma: no cover - optional dependency
	AutoTokenizer = None  # type: ignore[assignment]
	AutoModel = None  # type: ignore[assignment]
	torch = None  # type: ignore[assignment]
	torch_f = None  # type: ignore[assignment]

_HF_ENCODER = None
_HF_MODEL_NAME = None
_HF_TRUST_REMOTE_CODE = None

_COLBERT_TOKENIZER = None
_COLBERT_MODEL = None
_COLBERT_MODEL_NAME = None
_COLBERT_DEVICE = None


@dataclass
class Neo4jConfig:
	uri: str
	username: str
	password: str
	database: Optional[str]


@dataclass
class EmbeddingJobConfig:
	model: str
	provider: str
	description_property: str
	node_label: Optional[str]
	embedding_property: Optional[str]
	batch_size: int
	limit: Optional[int]
	trust_remote_code: bool
	colbert_pool: str
	sleep_seconds: float


def load_config_from_env() -> Neo4jConfig:
	"""Load Neo4j connection settings from .env or the environment."""
	load_dotenv()
	uri = os.getenv("NEO4J_URI")
	username = os.getenv("NEO4J_USERNAME")
	password = os.getenv("NEO4J_PASSWORD")
	database = os.getenv("NEO4J_DATABASE")

	if not uri or not username or not password:
		raise ValueError(
			"Missing Neo4j connection details. Please set NEO4J_URI, "
			"NEO4J_USERNAME, and NEO4J_PASSWORD in your .env file."
		)

	return Neo4jConfig(uri=uri, username=username, password=password, database=database)


def sanitize_property_name(model_name: str) -> str:
	"""Convert a model name into a safe Neo4j property name."""
	base = re.sub(r"[^a-zA-Z0-9_]+", "_", model_name.strip())
	base = base.strip("_") or "embedding"
	return f"{base}_embedding"


def build_read_query(description_property: str, node_label: Optional[str]) -> str:
	"""Build the query that pulls text to embed from Neo4j."""
	label_clause = f":{node_label}" if node_label else ""
	return (
		f"MATCH (n{label_clause}) "
		f"WHERE n[$desc_prop] IS NOT NULL "
		f"RETURN elementId(n) AS node_id, n[$desc_prop] AS text"
	)


def build_write_query(embedding_property: str) -> str:
	"""Build the query that stores embeddings back on each node."""
	if not re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", embedding_property):
		raise ValueError(
			"Embedding property name is invalid. Use only letters, numbers, and underscores, "
			"and do not start with a number."
		)
	return (
		"UNWIND $rows AS row "
		"MATCH (n) WHERE elementId(n) = row.node_id "
		f"SET n.{embedding_property} = row.embedding"
	)


def fetch_nodes(driver, database: Optional[str], read_query: str, desc_prop: str, limit: Optional[int]) -> List[dict]:
	"""Fetch node ids and description text from Neo4j."""
	params = {"desc_prop": desc_prop}
	if limit is not None:
		read_query = f"{read_query} LIMIT $limit"
		params["limit"] = limit

	with driver.session(database=database) as session:
		result = session.run(read_query, params)
		return [record.data() for record in result]


def chunked(iterable: List[dict], size: int) -> Iterable[List[dict]]:
	"""Yield fixed-size chunks from a list (for batching)."""
	for i in range(0, len(iterable), size):
		yield iterable[i : i + size]


def embed_texts_openai(model: str, texts: List[str]) -> List[List[float]]:
	"""Embed text using OpenAI's embedding API."""
	if OpenAI is None:
		raise ImportError("openai package is not installed. Install it to use OpenAI embeddings.")

	api_key = os.getenv("OPENAI_API_KEY")
	if not api_key:
		raise ValueError("OPENAI_API_KEY is missing in your .env file.")

	client = OpenAI(api_key=api_key)
	response = client.embeddings.create(model=model, input=texts)
	return [item.embedding for item in response.data]


def embed_texts_sentence_transformers(
	model: str,
	texts: List[str],
	batch_size: int,
	trust_remote_code: bool,
) -> List[List[float]]:
	"""Embed text using Hugging Face sentence-transformers models."""
	if SentenceTransformer is None:
		raise ImportError(
			"sentence-transformers package is not installed. Install it to use Hugging Face models."
		)

	global _HF_ENCODER, _HF_MODEL_NAME, _HF_TRUST_REMOTE_CODE
	if _HF_ENCODER is None or _HF_MODEL_NAME != model or _HF_TRUST_REMOTE_CODE != trust_remote_code:
		_HF_ENCODER = SentenceTransformer(model, trust_remote_code=trust_remote_code)
		_HF_MODEL_NAME = model
		_HF_TRUST_REMOTE_CODE = trust_remote_code

	encoder = _HF_ENCODER
	embeddings = encoder.encode(texts, batch_size=batch_size, convert_to_numpy=True, normalize_embeddings=True)
	return [embedding.tolist() for embedding in embeddings]


def embed_texts_voyage(model: str, texts: List[str]) -> List[List[float]]:
	"""Embed text using Voyage AI's embedding API."""
	if voyageai is None:
		raise ImportError("voyageai package is not installed. Install it to use Voyage AI embeddings.")

	api_key = os.getenv("VOYAGE_API_KEY")
	if not api_key:
		raise ValueError("VOYAGE_API_KEY is missing in your .env file.")

	client = voyageai.Client(api_key=api_key)
	response = client.embed(texts, model=model)
	return response.embeddings


def embed_texts_colbert(model: str, texts: List[str], pool: str) -> List[List[float]]:
	"""Embed text using ColBERT-style token embeddings via transformers."""
	if AutoTokenizer is None or AutoModel is None or torch is None or torch_f is None:
		raise ImportError("transformers/torch are not installed. Install them to use ColBERT models.")

	global _COLBERT_TOKENIZER, _COLBERT_MODEL, _COLBERT_MODEL_NAME, _COLBERT_DEVICE
	if _COLBERT_MODEL is None or _COLBERT_MODEL_NAME != model:
		_COLBERT_TOKENIZER = AutoTokenizer.from_pretrained(model)
		_COLBERT_MODEL = AutoModel.from_pretrained(model)
		_COLBERT_DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
		_COLBERT_MODEL.to(_COLBERT_DEVICE)
		_COLBERT_MODEL.eval()
		_COLBERT_MODEL_NAME = model

	inputs = _COLBERT_TOKENIZER(
		texts,
		padding=True,
		truncation=True,
		max_length=512,
		return_tensors="pt",
	)
	inputs = {key: value.to(_COLBERT_DEVICE) for key, value in inputs.items()}

	with torch.no_grad():
		outputs = _COLBERT_MODEL(**inputs, return_dict=True)
		last_hidden = outputs.last_hidden_state

	mask = inputs.get("attention_mask")
	if mask is None:
		raise ValueError("ColBERT model inputs missing attention_mask.")

	pool = pool.lower()
	if pool not in {"mean", "cls", "max"}:
		raise ValueError("ColBERT pooling must be one of: mean, cls, max.")

	all_embeddings: List[List[float]] = []
	for idx in range(last_hidden.size(0)):
		valid = mask[idx].bool()
		tokens = last_hidden[idx][valid]
		tokens = torch_f.normalize(tokens, p=2, dim=1)

		if pool == "cls":
			pooled = tokens[0]
		elif pool == "max":
			pooled = tokens.max(dim=0).values
		else:
			pooled = tokens.mean(dim=0)

		all_embeddings.append(pooled.cpu().tolist())

	return all_embeddings


def embed_texts(
	provider: str,
	model: str,
	texts: List[str],
	batch_size: int,
	trust_remote_code: bool,
) -> List[List[float]]:
	"""Route embedding requests to the chosen provider."""
	if provider == "openai":
		return embed_texts_openai(model, texts)
	if provider == "voyage":
		return embed_texts_voyage(model, texts)
	if provider == "hf":
		return embed_texts_sentence_transformers(model, texts, batch_size, trust_remote_code)
	if provider == "colbert":
		raise ValueError("ColBERT requires a pooling choice; use embed_texts_colbert in main().")
	raise ValueError("Unsupported provider. Use 'openai', 'voyage', 'hf', or 'colbert'.")


def write_embeddings(driver, database: Optional[str], write_query: str, rows: List[dict]) -> None:
	"""Write embeddings back to Neo4j in a single batch."""
	with driver.session(database=database) as session:
		session.run(write_query, {"rows": rows})


def parse_args() -> EmbeddingJobConfig:
	"""Parse CLI arguments to configure the embedding job."""
	parser = argparse.ArgumentParser(description="Generate and store embeddings for Neo4j nodes.")
	parser.add_argument(
		"--provider",
		choices=["openai", "voyage", "hf", "colbert"],
		required=True,
		help="Embedding provider.",
	)
	parser.add_argument("--model", required=True, help="Model name (e.g., text-embedding-3-small or BAAI/bge-m3).")
	parser.add_argument(
		"--description-property",
		default="App_Metadescription",
		help="Node property containing the text to embed.",
	)
	parser.add_argument("--node-label", default=None, help="Optional label to limit nodes.")
	parser.add_argument(
		"--embedding-property",
		default=None,
		help="Override embedding property name (default is <model>_embedding).",
	)
	parser.add_argument("--batch-size", type=int, default=64, help="Batch size for embedding and writing.")
	parser.add_argument("--limit", type=int, default=None, help="Limit number of nodes for testing.")
	parser.add_argument(
		"--trust-remote-code",
		action="store_true",
		help="Allow Hugging Face models that require custom code.",
	)
	parser.add_argument(
		"--colbert-pool",
		choices=["mean", "cls", "max"],
		default="mean",
		help="Pooling strategy for ColBERT token embeddings (stored as a single vector).",
	)
	parser.add_argument(
		"--sleep-seconds",
		type=float,
		default=0.0,
		help="Optional delay between batches (seconds) to respect rate limits.",
	)

	args = parser.parse_args()
	return EmbeddingJobConfig(
		model=args.model,
		provider=args.provider,
		description_property=args.description_property,
		node_label=args.node_label,
		embedding_property=args.embedding_property,
		batch_size=args.batch_size,
		limit=args.limit,
		trust_remote_code=args.trust_remote_code,
		colbert_pool=args.colbert_pool,
		sleep_seconds=args.sleep_seconds,
	)


def main() -> None:
	"""Run the full embedding pipeline: read -> embed -> write."""
	config = load_config_from_env()
	job = parse_args()

	# Determine which node property will store the embeddings.
	if job.embedding_property:
		embedding_property = job.embedding_property
	elif job.provider == "openai":
		embedding_property = f"openai_{sanitize_property_name(job.model)}"
	else:
		embedding_property = sanitize_property_name(job.model)

	# Build Cypher queries for reading and writing.
	read_query = build_read_query(job.description_property, job.node_label)
	write_query = build_write_query(embedding_property)

	driver = GraphDatabase.driver(config.uri, auth=(config.username, config.password))
	try:
		# Step 1: Fetch nodes and their description text.
		nodes = fetch_nodes(driver, config.database, read_query, job.description_property, job.limit)
		if not nodes:
			print("No nodes found with the specified description property.")
			return

		# Step 2: Embed in batches to avoid excessive memory usage.
		total = len(nodes)
		batch_count = (total + job.batch_size - 1) // job.batch_size
		for index, batch in enumerate(chunked(nodes, job.batch_size), start=1):
			print(f"Processing batch {index}/{batch_count} ({len(batch)} items)...")
			texts = [item["text"] for item in batch]
			if job.provider == "colbert":
				embeddings = embed_texts_colbert(job.model, texts, job.colbert_pool)
			else:
				embeddings = embed_texts(
					job.provider,
					job.model,
					texts,
					job.batch_size,
					job.trust_remote_code,
				)

			# Step 3: Write embeddings back to the corresponding nodes.
			rows = [
				{"node_id": item["node_id"], "embedding": embedding}
				for item, embedding in zip(batch, embeddings)
			]
			write_embeddings(driver, config.database, write_query, rows)
			print(f"Finished batch {index}/{batch_count}.")
			if job.sleep_seconds > 0 and index < batch_count:
				print(f"Sleeping for {job.sleep_seconds} seconds to respect rate limits...")
				time.sleep(job.sleep_seconds)

		print(f"Stored embeddings in property '{embedding_property}' for {len(nodes)} nodes.")
	finally:
		driver.close()


if __name__ == "__main__":
	main()
